spring:
  application:
    name: transaction-service
  config:
    import: optional:configserver:http://localhost:8889
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: transaction-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: transactionRequest:com.lsi.transaction.dto.request.TransactionRequest
        spring.json.use.type.headers: false





management:
  endpoints:
    web:
      exposure:
        include: "*"
