apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-deploy
  labels:
    app: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: ${ECR_REGISTRY}/transaction-service:latest
          ports:
            - containerPort: 8599
          envFrom:
            - configMapRef:
                name: transaction-service-config
            - secretRef:
                name: transaction-service-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8599
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8599
            initialDelaySeconds: 60
            periodSeconds: 15
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "200m"