apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: fintech
spec:
  type: LoadBalancer
  ports:
    - port: 8599
      targetPort: 8599
  selector:
    app: transaction-service